name: PHPCS WordPress Standards

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer
        run: composer install --no-progress --prefer-dist

      - name: Install PHPCS and WPCS
        run: |
          # pin versions to ensure reproducible CI runs
          composer global require "squizlabs/php_codesniffer:^3.7"
          composer global require "wp-coding-standards/wpcs:^2.3"
          ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Run PHPCS
        run: |
          ~/.composer/vendor/bin/phpcs --standard=WordPress --ignore=vendor --extensions=php ./wp-content/plugins/pnpc-pocket-service-desk